CREATE DATABASE IF NOT EXISTS tinylink CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tinylink;

CREATE TABLE IF NOT EXISTS links (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(8) NOT NULL UNIQUE,
  target_url TEXT NOT NULL,
  total_clicks INT UNSIGNED NOT NULL DEFAULT 0,
  last_clicked DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
